spring:
  data:
    mongodb:
      uri: "mongodb+srv://marlonfcosta90:1HhW07spwd7nwnqx@cluster0.onm2dkj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: "snackhubpaydev"

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

management:
  endpoints:
    web:
      base-path: /manage

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enable: true

mp:
  url: https://api.mercadopago.com
  authorization: Bearer APP_USR-3823682881313300-012901-e7d2a4ceac371c9774c46ee0297208db-1589696702
  userId: 1589696702
  externalId: SNACKBARPOTESTSELLER

api:
  qr-server:
    create-qr-code:
      url: https://api.qrserver.com/v1/create-qr-code

access:
  token:
    seller: APP_USR-3823682881313300-012901-e7d2a4ceac371c9774c46ee0297208db-1589696702

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: AKIAYS2NV2ZOVDEG7CPX
      secret-key: 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
      use-default-aws-credentials-chain: false
      instance-profile: false
    endpoint:
      uri: https://mfc24cloud.signin.aws.amazon.com/
    queue:
      receive-order-queue:
        url: https://sqs.us-east-1.amazonaws.com/590184044125/receive-order-topic
        name: receive-order-topic
      order-status-queue:
        url: https://sqs.us-east-1.amazonaws.com/590184044125/order-status-topic
        name: order-status-topic
      payment-status-queue:
        url: https://sqs.us-east-1.amazonaws.com/590184044125/payment-status-topic
        name: payment-status-topic