spring:
  data:
    mongodb:
      schema: snackhubpaytest
      uri: mongodb://localhost
      port: 27017

api:
  qr-server:
    create-qr-code:
      url: https://api.qrserver.com/v1/create-qr-code

access:
  token:
    seller: APP_USR-3823682881313300-012901-e7d2a4ceac371c9774c46ee0297208db-1589696702

mp:
  url: https://api.mercadopago.com
  authorization: Bearer APP_USR-3823682881313300-012901-e7d2a4ceac371c9774c46ee0297208db-1589696702
  userId: 1589696702
  externalId: SNACKBARPOTESTSELLER