spring:
  data:
    mongodb:
      schema: snackhubpaytest
      uri: mongodb://localhost
      port: 27017

api:
  qr-server:
    create-qr-code:
      url: https://api.qrserver.com/v1/create-qr-code

access:
  token:
    seller: XXXXXXXXXXXXXXX

mp:
  url: https://api.mercadopago.com
  authorization: XXXXXXXXXXX
  userId: XXXXXXXXXX
  externalId: XXXXXXXXXXXXXX