spring:
  data:
    mongodb:
      schema: snackhubpaydev
      uri: mongodb://localhost
      port: 27017

server:
  port: 8090
  undertow:
    threads:
      worker: 10
      io: 2

management:
  endpoints:
    web:
      base-path: /manage

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enable: true

mp:
  url: "https://api.mercadopago.com"
  authorization: "Bearer APP_USR-3823682881313300-012901-e7d2a4ceac371c9774c46ee0297208db-1589696702"
  userId: "1589696702"
  externalId: "SNACKBARPOTESTSELLER"

api:
  qr-server:
    create-qr-code:
      url: "https://api.qrserver.com/v1/create-qr-code"

access:
  token:
    seller: "APP_USR-3823682881313300-012901-e7d2a4ceac371c9774c46ee0297208db-1589696702"

cloud:
  aws:
    stack:
      auto: false
    region:
      static: sa-east-1
    credentials:
      access-key: localhost
      secret-key: localhost
    end-point:
      uri: http://localhost:4566
    queue:
      order-queue:
        url: "http://localhost:4566/000000000000/order-topic"
        name: "order-topic"
      order-status-queue:
        url: "http://localhost:4566/000000000000/order-status-topic"
        name: "order-status-topic"
      payment-status-queue:
          url: "http://localhost:4566/000000000000/payment-status-topic"
          name: "payment-status-topic"
      notification-queue:
        url: "http://localhost:4566/000000000000/notification-mp-topic"
        name: "notification-mp-topic"

      dead-letter-queue:
        url: "http://localhost:4566/000000000000/snackhub-pay-queue-dead-letter"
        name: "snackhub-pay-queue-dead-letter"
      max-receive-count: 3
      visibility-timeout: 30
      delay-seconds: 0
      message-retention-period: 1209600
      receive-message-wait-time: 0
      redrive-policy: "
      {\"deadLetterTargetArn\":\"arn:aws:sqs:sa-east-1:000000000000:snackhub-pay-queue-dead-letter\",\"maxReceiveCount\":3}"