mongodb:
  username: root
  password: root
  schema: snackhubpay
  url: snackhubpay-mongodb
  port: 27017
  #url: 127.0.0.1:3307

server:
  port: 8090
  undertow:
    threads:
      worker: 10
      io: 2

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enable: true

mp:
  url: "https://api.mercadopago.com"

api:
  qr-server:
    create-qr-code:
      url: "https://api.qrserver.com/v1/create-qr-code"