spring:
  data:
    mongodb:
      uri: "mongodb+srv://marlonfcosta90:X@cluster0.onm2dkj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: "snackhubpaydev"

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

management:
  endpoints:
    web:
      base-path: /manage

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enable: true

mp:
  url: "https://api.mercadopago.com"
  authorization: "X"
  userId: "X"
  externalId: "X"

api:
  qr-server:
    create-qr-code:
      url: "https://api.qrserver.com/v1/create-qr-code"

access:
  token:
    seller: "X"

cloud:
  aws:
    stack:
      auto: false
    region:
      static: sa-east-1
    credentials:
      access-key: localhost
      secret-key: localhost
    end-point:
      uri: http://localhost:4566
    queue:
      order-queue:
        url: "http://localhost:4566/000000000000/order-topic"
        name: "order-topic"
      order-status-queue:
        url: "http://localhost:4566/000000000000/order-status-topic"
        name: "order-status-topic"
      payment-status-queue:
          url: "http://localhost:4566/000000000000/payment-status-topic"
          name: "payment-status-topic"
      notification-queue:
        url: "http://localhost:4566/000000000000/notification-mp-topic"
        name: "notification-mp-topic"