version: '3.7'

services:
  snackhubpay-mongodb:
    container_name: snackhubpay-mongodb
    restart: always
    image: 'mongo:latest'
    environment:
        - MONGO_INITDB_DATABASE=snackhubpay
        - MONGO_INITDB_ROOT_USERNAME=
        - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - "27017"
    networks:
      - snackhubpay_network
networks:
  snackhubpay_network:
    driver: bridge
    name: snackhubpay_network
volumes:
  db: