# Use an official Maven image as the base image
#docker build -f Dockerfile.dev -t marlonfc90/snackhubpay-app:latest .
#docker push marlonfc90/snackhubpay-app
#docker-compose up -d

FROM maven:3.8.4-openjdk-17-slim AS build

# Set the working directory in the container
WORKDIR /usr/app

COPY . .

# Build the application using Maven
RUN mvn clean package -DskipTests

# Use an official OpenJDK image as the base image
FROM eclipse-temurin:17.0.5_8-jre-alpine

# Copy the built JAR file from the previous stage to the container
COPY --from=build /usr/app/infrastructure/target/*.jar /opt/app/snackhubpay.jar

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Set the command to run the application
CMD java -jar /opt/app/snackhubpay.jar