#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build

WORKDIR /usr/app/

COPY . .

RUN mvn -X -f /usr/app/pom.xml clean package

#
# Package stage
#
FROM eclipse-temurin:17-jdk-alpine
COPY --from=build /usr/app/target/snackhub-payments /usr/local/lib/snackhub-payments.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/snackhub-payments.jar"]



